
(require 'lazycat-toolkit)
(require 'dash-at-point)
(require 'move-text)
(require 'duplicate-line)
(require 'goto-last-change)
(require 'open-newline)
(require 'smart-align)
(require 'restart-emacs)
(require 'recursive-search-references)
(require 'tiny)
(require 'expand-region)
(require 'string-inflection)
(require 'ace-jump-mode)

(provide 'init-misc)
